apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mul
spec:
  replicas: 1
  template:
    metadata:
      labels:
        prod: socra
        app: mul
    spec:
      containers:
      - name: service
        image: socra-mul:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
        securityContext:
          readOnlyRootFilesystem: true
