FROM golang:1.12.10-buster

WORKDIR /go/src/github.com/symflower/sessions/2019/socrates-linz

RUN go get -v -u github.com/zimmski/go-mutesting/cmd/go-mutesting github.com/PuerkitoBio/goquery github.com/mattn/go-sqlite3 github.com/leanovate/gopter github.com/securego/gosec/cmd/gosec github.com/stretchr/testify/assert
